service: serverless-example

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: src/index.hello
    events:
      - http:
          path: hello
          method: get
